# ============================================================================
# ExternalSecret - PetClinic DB 자격증명
# ============================================================================
# ⚠️ 이 파일은 petclinic-gitops 레포에 배치하세요!
# ============================================================================
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: petclinic-db-secret
  namespace: petclinic
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: petclinic-db-secret
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_URL
      remoteRef:
        # ⚠️ 실제 Secret 이름으로 변경 (02-compute output 참조)
        key: petclinic-kr/db
        property: SPRING_DATASOURCE_URL
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: petclinic-kr/db
        property: SPRING_DATASOURCE_USERNAME
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: petclinic-kr/db
        property: SPRING_DATASOURCE_PASSWORD
