# ============================================================================
# platform-gitops/platform/karpenter-config/templates/ec2nodeclass.yaml
# ============================================================================
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
  annotations:
    kubernetes.io/description: "Default EC2NodeClass for general workloads"
spec:
  # AMI 선택 - AL2023 EKS 최적화
  amiSelectorTerms:
    - alias: al2023@latest

  # IAM Role (Terraform에서 생성)
  role: {{ .Values.ec2NodeClass.roleName }}

  # Subnet 선택 (태그 기반)
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.clusterName }}

  # Security Group 선택 (태그 기반)
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: {{ .Values.clusterName }}

  # 블록 디바이스 설정
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: {{ .Values.ec2NodeClass.ebs.volumeSize }}
        volumeType: {{ .Values.ec2NodeClass.ebs.volumeType }}
        iops: {{ .Values.ec2NodeClass.ebs.iops }}
        throughput: {{ .Values.ec2NodeClass.ebs.throughput }}
        encrypted: {{ .Values.ec2NodeClass.ebs.encrypted }}
        deleteOnTermination: {{ .Values.ec2NodeClass.ebs.deleteOnTermination }}

  # IMDS 설정 (IMDSv2 필수)
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required

  # 태그
  tags:
    Name: "{{ .Values.clusterName }}-karpenter-node"
    Project: "petclinic-kr"
    Environment: "production"
    ManagedBy: "karpenter"
    "karpenter.sh/discovery": "{{ .Values.clusterName }}"